Add UNIX lesson
nih-cfde/training-and-engagement pull request #537
Opened 2022-06-01 19:26 UTC by raynamharris

[WIP]

## PR Checklist

- [ ] Release label added
- [ ] PR category label added
- [ ] PR mergeable
- [ ] Clean build logs
- [ ] Linked related issues
- [ ] Colorblindness test https://www.toptal.com/designers/colorfilter/

## PR Description
Briefly describe the changes this PR will add/address
**Preview link**
Add the RTD auto generated preview link

## Review format
Add how you would like to receive the review (direct editing, as comments, notes etc)

## Timeline
Add expected timeline to finish review and merge adding note for time critical updates

2022-06-03 15:34 UTC, raynamharris commented
thanks @jeremywalter !

2022-06-04 18:17 UTC, raynamharris commented
closes #539

2022-06-04 18:18 UTC, raynamharris commented
will likely have conflicts with #535 with the .pages file due to both lessons needing to be added to the nav bar. i plan on merging this one first and fixing the conflict in the other second.

2022-06-20 16:31 UTC, raynamharris commented
thanks jeremy. excellent updates. ready for approval

2022-06-21 19:08 UTC, jessicalumian requested changes
I made typo fixes, and the biggest thing was changing the code in the appendix.md file. I ran through the lesson code in an RStudio binder and it all worked. The code in the appendix.md file did not match what was in the lesson, so I made a bunch of suggestions to make that code match.

Happy to change this to "approve" now if there's a logistical reason. Otherwise I'll set this to "Request Changes" and "Approve" later.

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/find.md
> +The `MiSeq/` directory contains many of the sequence files ending in`.fastq`. We expect these files to contain information in a particular format throughout the file with four lines of information fo
```suggestion
The `MiSeq/` directory contains many of the sequence files ending in`.fastq`. We expect these files to contain information in a particular format throughout the file with four lines of information for each sequence string. Looking through a million-line file using less will take a long time. Rather than manually looking at the whole file, we can print only a portion of the file's contents to standard output. 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/find.md
> +Let's say you'd like to find the sequence `CATTAG` in your MiSeq files. We can use function `grep` to search for  `CATTAG` in one or all all of the fastq files located in our current working director
```suggestion
Let's say you'd like to find the sequence `CATTAG` in your MiSeq files. We can use the function `grep` to search for  `CATTAG` in one or all of the fastq files located in our current working directory.
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/navigate.md
> +Now we have seen how to list the contents of folders on our computers and what is located in the directory we are presently in. But some of the beauty of the shell is that we can perform activities i
```suggestion
Now we have seen how to list the contents of folders on our computers and what is located in the directory we are presently in. But some of the beauty of the shell is that we can perform activities in locations that we are not currently in. To do this we can either use an absolute path or a relative path. A **relative path** is the path to another directory from the one you are currently in. An **absolute path** starts from the root and ends in the appropriate subdirectory. 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/read.md
> +The `cat` command prints the entirety of a file to the stdout of our computer. We can scroll through files using the `less` command. Less is a safe way of looking at the contents of a file without th
```suggestion
The `cat` command prints the entirety of a file to the stdout of our computer. We can scroll through files using the `less` command. Less is a safe way of looking at the contents of a file without the ability to change it. `head` prints, by default, the first 10 lines of a file and `tail` prints the last 10 lines.
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/redirect.md
> +Let's pipe (`|`) the output of a grep search to the command head to only show the first 10 lines. This is very handy when you only want to view snapshot of the data.
```suggestion
Let's pipe (`|`) the output of a grep search to the command head to only show the first 10 lines. This is very handy when you only want to view a snapshot of the data. 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/redirect.md
> +However, the two lines above told us, how many times CATTAG appeared in all of the .fastq files in total.
```suggestion
However, the two lines above tell us how many times CATTAG appeared in all of the .fastq files in total. 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/redirect.md
> +If we cant to know which file these results came from, we can add an echo statement to echo the variable.
```suggestion
If we want to know which file these results came from, we can add an echo statement to echo the variable.
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/redirect.md
> +You can redirect the output from the screen to a file using `>`. Note that `>` will overright existing conent, but `>>` will append.
```suggestion
You can redirect the output from the screen to a file using `>`. Note that `>` will overwrite existing content, but `>>` will append. 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/work.md
> +The first line creates two directories, results and images. The second line also create two directories, but they are nested with the parent directory data.
```suggestion
The first line creates two directories, results and images. The second line also creates two directories, but they are nested with the parent directory data. 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/work.md
> +`rmdir` will only remove empty directories, but `rm -r` will remove recursively.
```suggestion
`rmdir` will only remove empty directories, but `rm -r` will remove them recursively.
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +pwd
```suggestion
PS1='$ '
clear
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +PS1="\w $ "
```suggestion

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls -l books
```suggestion
cd books/
pwd
ls -lh
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls -l MiSeq
```suggestion

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls -lh MiSeq
```suggestion

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls -lh *
```suggestion

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cd books
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +pwd
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cd ../Miseq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +pwd
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls *fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +ls F3*
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cd ~books
```suggestion
cd ~/books/
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +head *txt
```suggestion
head *.txt
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *txt | sort
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *txt | sort -nr
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *txt | sort -nr
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
cp book.txt book-copy.txt
ls

mv book-copy.txt book-2cities.txt

mkdir data results images/
mkdir -p data/results/images

rmdir data/results/images
rmdir data/results

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +rm book.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +mkdir results
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *txt | sort -nr > results/book_lengths.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cat results/book_lengths.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "Chapter" *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep -i "Chapter" *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "CHAPTER" *txt > results/chapter_titles.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cat results/chapter_titles.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "The" *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^The" *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep -w "^The" *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep -w -A 1 "^The" *txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep -w  "^The" *txt > results/The.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cat results/The.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
cd ~/MiSeq
ls

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +head README.md
```suggestion

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +less F3D0_S188_L001_R1_001.fastq
```suggestion
head -4 HMP_MOCK.v35.fasta 
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc README.md
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc F3D0_S188_L001_R1_001.fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l F3D0_S188_L001_R1_001.fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *R1*fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +wc -l *R1*fastq | sort -nr
```suggestion
cd ../data/MiSeq/
grep CATTAG F3D0_S188_L001_R2_001.fastq
grep CATTAG *.fastq
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +head -4 F3D0_S188_L001_R1_001.fastq
```suggestion
wc F3D0_S188_L001_R2_001.fastq
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^@M" F3D0_S188_L001_R1_001.fastq
```suggestion
wc -l F3D0_S188_L001_R2_001.fastq

```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^@M" F3D0_S188_L001_R1_001.fastq | wc -l
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^@M" *R1*.fastq | wc -l
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
mkdir results
grep CATTAG *.fastq > results/files-with-CATTAG.txt

grep CATTAG *.fastq 
grep CATTAG *.fastq | wc -l
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +for file in *R1*.fastq
```suggestion
for file in *fastq
do
grep CATTAG $file | wc -l
done
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +do
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +echo $file
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^@M" $file | wc -l
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +done
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
history

history > ~/history-2021-nov-17.txt
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +for file in *R1*.fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +do
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +echo $file >> results/read_count.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^@M" $file | wc -l >> results/read_count.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +done
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +head results/read_count.txt
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +for file in *R1*.fastq
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +do
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +echo $file >> results/samples.csv
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +grep "^@M" $file | wc -l >> results/count.csv
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +paste -d , results/samples.csv results/count.csv > results/read_count.csv
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +done
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +head results/read_count.csv
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +cd
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +history
```suggestion
```

2022-06-21 19:08 UTC, jessicalumian commented on docs/General-Tools/UNIX/appendix.md
> +history > history.txt
```suggestion
```

2022-06-21 19:29 UTC, raynamharris commented
awesome! thanks @jessicalumian changes incorporated

2022-06-21 19:35 UTC, jessicalumian approved these changes

2022-06-21 19:46 UTC, raynamharris commented on docs/General-Tools/UNIX/appendix.md
> +ls -l books
keeping as is

2022-06-21 19:46 UTC, raynamharris commented on docs/General-Tools/UNIX/appendix.md
> +ls -lh MiSeq
keeping as is

2022-06-21 22:54 UTC, jeremywalter commented
couple last minute fixes coming (on the latter pages)... please hold...

2022-06-23 17:06 UTC, merged

2022-06-23 17:13 UTC, raynamharris commented
looks good :)

![Uploading Screen Shot 2022-06-23 at 10.13.04 AM.png…]()